name: Automatic Maven Build

on:
  workflow_dispatch: {}
  schedule:
  - cron: '*/10 * * * *'

jobs:
  build:
    name: Automatic Maven Build
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      BOT_EMAIL: ${{ secrets.BOT_EMAIL }}

    steps:
    - name: Checking out Repository
      uses: actions/checkout@master

    - name: Setting up Java
      uses: actions/setup-java@v3.0.0
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Setting up node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: '16.13.0'

    - name: Installing dependencies
      run: yarn

    - name: Setup environment
      run: sh src/maven-build-setup.sh

    - name: Run automatic build
      id: maven-build
      run: node src/maven-build.js

    - name: Trigger nuxt build
      if: steps.maven-build.outputs.HAS_UPDATE == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.BOT_TOKEN }}
        event-type: nuxt-build
