name: Validate repos.json

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-repos:
    name: Validate repos.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Validate repos.json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /static/schema.json
          INPUT_JSONS: /static/repos.json