name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: "ybw0014"
          reponame: "maven-builds"
          token: ${{ secrets.GITHUB_TOKEN }}
          gitemail: "no-reply@guizhanss.com"
          gitname: "GuizhanBot"

